# Generated by Django 2.0.7 on 2019-05-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0004_recrutareprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now=True, null=True)),
                ('lider', models.ForeignKey(db_column='fk_user_avancado', on_delete=django.db.models.deletion.PROTECT, to='usuario.UserAvancado')),
            ],
            options={
                'db_table': 'tb_grupos',
            },
        ),
        migrations.CreateModel(
            name='VinculoGrupos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(auto_now=True, null=True)),
                ('grupo', models.ForeignKey(db_column='fk_grupo', on_delete=django.db.models.deletion.PROTECT, to='core.Grupos')),
                ('membro', models.ForeignKey(db_column='fk_user_avancado', on_delete=django.db.models.deletion.PROTECT, to='usuario.UserAvancado')),
            ],
            options={
                'db_table': 'tb_vinculo_grupos',
            },
        ),
    ]
