# Generated by Django 2.0.7 on 2019-05-28 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_recrutareprovado'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnunciosGerais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=800)),
                ('data_cadastro', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.ForeignKey(db_column='fk_user_avancado', on_delete=django.db.models.deletion.PROTECT, to='usuario.UserAvancado')),
            ],
            options={
                'db_table': 'tb_anuncios_gerais',
            },
        ),
    ]
