# Generated by Django 2.0.7 on 2019-06-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_recrutareprovado'),
        ('core', '0003_anunciosrestritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guerras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(1, 'Nodewar'), (2, 'Siege')], default=1)),
                ('modelo', models.IntegerField(choices=[(1, 'Oficial'), (2, '4Fun')], default=1)),
                ('data_inicio', models.DateField()),
                ('pt_fixa', models.BooleanField(default=True)),
                ('quantidade_players', models.IntegerField(blank=True, null=True)),
                ('servidor', models.CharField(blank=True, max_length=50, null=True)),
                ('node', models.CharField(blank=True, max_length=50, null=True)),
                ('call', models.ForeignKey(blank=True, db_column='call_user_avancado', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.UserAvancado')),
            ],
            options={
                'db_table': 'tb_guerras',
            },
        ),
    ]
