# Generated by Django 2.0.7 on 2019-06-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_recrutareprovado'),
        ('core', '0004_guerras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticiparGuerra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participa', models.CharField(choices=[('Sim', 'Sim'), ('Talvez', 'Talvez'), ('Não', 'Não')], default='Sim', max_length=10)),
                ('guerra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Guerras')),
                ('participante', models.ForeignKey(db_column='fk_user_avancado', on_delete=django.db.models.deletion.PROTECT, to='usuario.UserAvancado')),
            ],
            options={
                'db_table': 'tb_participar_guerra',
            },
        ),
    ]
