# Generated by Django 2.0.7 on 2019-07-01 20:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_participarguerra'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaGuerra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participantes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
                ('guerra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Guerras')),
            ],
            options={
                'db_table': 'tb_frequencia_guerra',
            },
        ),
    ]
