# Generated by Django 2.0.7 on 2019-07-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_update_name_guerreiro'),
        ('core', '0006_frequenciaguerra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('url_print_payout', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tb_payout',
            },
        ),
        migrations.CreateModel(
            name='PayoutPersonalizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tier_adicional', models.IntegerField()),
                ('payout', models.ForeignKey(db_column='fk_payout', on_delete=django.db.models.deletion.PROTECT, to='core.Payout')),
                ('usuario', models.ForeignKey(db_column='fk_user_avancado', on_delete=django.db.models.deletion.PROTECT, to='usuario.UserAvancado')),
            ],
            options={
                'db_table': 'tb_payout_personalizado',
            },
        ),
    ]
