# Generated by Django 2.0.7 on 2019-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payout_payoutpersonalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_variavel', models.CharField(max_length=100)),
                ('slug_variavel', models.CharField(max_length=200)),
                ('tipo_variavel', models.IntegerField(choices=[(0, 'String'), (1, 'Inteiro'), (2, 'Booleano')])),
                ('valor_inteiro', models.IntegerField(blank=True, null=True)),
                ('valor_string', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_bool', models.NullBooleanField()),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tb_configuracoes',
            },
        ),
    ]
