# Generated by Django 2.0.7 on 2019-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_criando_primeiras_variaveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoCondicoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tb_termo_condicoes',
            },
        ),
    ]
