# Generated by Django 2.0.7 on 2019-08-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_termocondicoes'),
    ]

    operations = [
        migrations.RunSQL('''
          INSERT INTO tb_termo_condicoes (texto) VALUES (
          'Nenhum Termo e Condições para Recrutamento e Participação da Guilda foi escrito.');
        '''),
    ]
