# Generated by Django 2.0.7 on 2019-09-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_migrate_cores'),
    ]

    operations = [
        migrations.RunSQL('''
          INSERT INTO tb_configuracoes (nome_variavel, slug_variavel, tipo_variavel, valor_string) VALUES (
          'site_guilda', 'Site da Guilda', 0, '');
        '''),
        migrations.RunSQL('''
          INSERT INTO tb_configuracoes (nome_variavel, slug_variavel, tipo_variavel, valor_inteiro, descricao) VALUES (
          'fechamento_war', 'Fechamento das Participações', 1, 22, 'Hora do fechamento para participações da guerra do dia.');
        '''),
        migrations.RunSQL('''
          INSERT INTO tb_configuracoes (nome_variavel, slug_variavel, tipo_variavel, valor_inteiro, descricao) VALUES (
          'tier_por_node', 'Quantos Tier por Nodewar', 1, 1, 'Quantidade de tier para cálculo automático da frequência de guerra');
        '''),
        migrations.RunSQL('''
          INSERT INTO tb_configuracoes (nome_variavel, slug_variavel, tipo_variavel, valor_inteiro, descricao) VALUES (
          'tier_por_siege', 'Quantos Tier por Siege', 1, 2, 'Quantidade de tier para cálculo automático da frequência de guerra');
        '''),
    ]
