# Generated by Django 2.0.7 on 2019-10-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_criando_mais_configuracoes'),
    ]

    operations = [
        migrations.RunSQL('''
          INSERT INTO tb_configuracoes (nome_variavel, slug_variavel, tipo_variavel, valor_inteiro, descricao) VALUES (
          'limitacao_membro', 'Limitações para Membros', 1, 0, 'Limitações de Membros para acessos visuais a algumas informações de outros membros.');
        '''),
        migrations.RunSQL('''
          INSERT INTO tb_configuracoes (nome_variavel, slug_variavel, tipo_variavel, valor_inteiro, descricao) VALUES (
          'limitacao_heroi', 'Limitações para Heróis', 1, 0, 'Limitações de Heróis para acessos visuais a algumas informações do sistema.');
        '''),
    ]
