# Generated by Django 2.0.7 on 2019-11-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_criar_configuracao_limitacoes_heroi_membro'),
    ]

    operations = [
        migrations.RunSQL('''
          INSERT INTO tb_configuracoes (nome_variavel, slug_variavel, tipo_variavel, valor_inteiro, descricao) VALUES (
          'variavel_frequencia_alerta', 'Frequência Mínima nas Guerras', 1, 2, 'Variável que define a quantidade aceitável de frequência nas Guerras por Semana. Igual ou abaixo deste valor, surge um alerta para o Membro(ou Líder, ou Oficial).');
        '''),
    ]
