# Generated by Django 2.0.7 on 2019-04-23 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoClasseChar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_classe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_tipo_classe_char',
            },
        ),
        migrations.CreateModel(
            name='UserAvancado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_discord', models.CharField(max_length=50)),
                ('nome_familia', models.CharField(max_length=30)),
                ('nome_char_principal', models.CharField(max_length=30)),
                ('char_lvl', models.IntegerField()),
                ('char_ap', models.IntegerField()),
                ('char_ap_despertada', models.IntegerField()),
                ('char_dp', models.IntegerField()),
                ('gs', models.IntegerField()),
                ('url_print_status', models.CharField(max_length=100)),
                ('siege', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('node_seg', models.BooleanField(default=False)),
                ('node_ter', models.BooleanField(default=False)),
                ('node_qua', models.BooleanField(default=False)),
                ('node_qui', models.BooleanField(default=False)),
                ('node_sex', models.BooleanField(default=False)),
                ('node_dom', models.BooleanField(default=False)),
                ('cargo', models.IntegerField(choices=[(1, 'Líder'), (2, 'Oficial'), (3, 'Membro')], default=4)),
                ('ativo', models.BooleanField(default=False)),
                ('justificativa_inativo', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True, null=True)),
                ('char_classe', models.ForeignKey(db_column='fk_tipo_classe_char', on_delete=django.db.models.deletion.PROTECT, to='usuario.TipoClasseChar')),
                ('usuario', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_user_avancado',
            },
        ),
    ]
