# Generated by Django 2.0.7 on 2019-04-19 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoClasseChar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_classe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_tipo_classe_char',
            },
        ),
        migrations.CreateModel(
            name='UserAvancado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_real', models.CharField(max_length=50)),
                ('nome_familia', models.CharField(max_length=30)),
                ('nome_char_principal', models.CharField(max_length=30)),
                ('char_lvl', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now=True, null=True)),
                ('char_classe', models.ForeignKey(db_column='fk_tipo_classe_char', on_delete=django.db.models.deletion.PROTECT, to='usuario.TipoClasseChar')),
                ('usuario', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_user_avancado',
            },
        ),
    ]
