# Generated by Django 2.0.7 on 2019-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_insert_tipos_classe_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravancado',
            name='node_dom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useravancado',
            name='node_qua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useravancado',
            name='node_qui',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useravancado',
            name='node_sab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useravancado',
            name='node_seg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useravancado',
            name='node_sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useravancado',
            name='node_ter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useravancado',
            name='siege',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useravancado',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Líder'), (2, 'Oficial'), (3, 'Membro')], default=4),
        ),
    ]
