# Generated by Django 2.0.7 on 2019-04-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_insert_tipos_classe_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravancado',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Líder'), (2, 'Oficial'), (5, 'Quartel-mestre'), (3, 'Membro')], default=4),
        ),
    ]
