# Generated by Django 2.0.7 on 2019-05-18 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0003_auto_20190424_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecrutaReprovado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('justificativa', models.CharField(max_length=500)),
                ('data_cadastro', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_recruta_reprovado',
            },
        ),
    ]
