# Generated by Django 2.0.7 on 2019-04-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190421_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravancado',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useravancado',
            name='siege',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True),
        ),
    ]
