# Generated by Django 2.0.7 on 2019-04-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20190421_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravancado',
            name='node_sab',
        ),
    ]
