# Generated by Django 2.0.7 on 2019-06-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_recrutareprovado'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO tb_tipo_classe_char (nome_classe) VALUES ('shai');")
    ]
