# Generated by Django 2.0.7 on 2019-07-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_insert_shai'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravancado',
            name='url_bdo_planner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
