# Generated by Django 2.0.7 on 2019-07-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_useravancado_url_bdo_planner'),
    ]

    operations = [
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET nome_classe='guerreiro' WHERE nome_classe='cavaleiro';")
    ]
