# Generated by Django 2.0.7 on 2019-08-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_update_name_guerreiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravancado',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Líder'), (2, 'Oficial'), (5, 'Quartel-mestre'), (3, 'Membro'), (6, 'Herói')], default=4),
        ),
    ]
