# Generated by Django 2.0.7 on 2019-08-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20190801_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravancado',
            name='recruta_para_ser',
            field=models.IntegerField(choices=[(3, 'Membro'), (6, 'Herói')], default=3),
        ),
    ]
