# Generated by Django 2.0.7 on 2019-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_useravancado_recruta_para_ser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoclassechar',
            name='slug',
            field=models.CharField(default='indefinido', max_length=50),
        ),
    ]
