# Generated by Django 2.0.7 on 2019-08-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_tipoclassechar_slug'),
    ]

    operations = [
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Guerreiro' WHERE nome_classe='guerreiro';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Valkyria' WHERE nome_classe='valkyria';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Berserker' WHERE nome_classe='berserker';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Caçadora' WHERE nome_classe='cacadora';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Arqueiro' WHERE nome_classe='arqueiro';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Mago' WHERE nome_classe='mago';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Bruxa' WHERE nome_classe='bruxa';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Feiticeira' WHERE nome_classe='feiticeira';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Ninja' WHERE nome_classe='ninja';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Kunoichi' WHERE nome_classe='kunoichi';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Musa' WHERE nome_classe='musa';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Maehwa' WHERE nome_classe='maehwa';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Tamer' WHERE nome_classe='tamer';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Mística' WHERE nome_classe='mistica';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Lutador' WHERE nome_classe='striker';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Lahn' WHERE nome_classe='lahn';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Cavaleira das Trevas' WHERE nome_classe='dark_knight';"),
        migrations.RunSQL("UPDATE tb_tipo_classe_char SET slug='Shai' WHERE nome_classe='shai';"),
    ]
