# Generated by Django 2.0.7 on 2020-09-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_add_new_classe_guardian'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO tb_tipo_classe_char (nome_classe, slug) VALUES ('hashashin', 'Hashashin');")
    ]
